services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    networks:
      - monopoly-network

  frontend:
    build: ./frontend
    ports:
      - "8002:8002"
    depends_on:
      - backend
    networks:
      - monopoly-network

networks:
  monopoly-network:
    driver: bridge