version: '3.8'

services:
  monopoly-app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - ./backend/data:/app/backend/data
    environment:
      - PORT=8002
    restart: always
